variable "env" {}
variable "tags" {}
variable "default_vpc_id" {}
variable "default_route_table" {}
variable "vpc" {}
variable "docdb" {}
variable "backup_retention_period" {}
variable "preferred_backup_window" {}
variable "skip_final_snapshot" {}
